spring:
  application:
    name: auth-service

  config:
    import: "optional:configserver:${CONFIG_SERVER_URI:http://config-server:8888}"

  cloud:
    config:
      username: ${CONFIG_SERVER_USERNAME:config-user}
      password: ${CONFIG_SERVER_PASSWORD:config-secret}
      fail-fast: false
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000


  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET:desco-super-secret-key-must-be-at-least-256-bits-long-for-hs256}
  access-token-expiration: 900000       # 15 min
  refresh-token-expiration: 604800000   # 7 days

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.desco.authservice: DEBUG
